/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int AQHE = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int SWITCH = 19;
  /** RegularExpression Id. */
  int CASE = 20;
  /** RegularExpression Id. */
  int DEFAULT_KW = 21;
  /** RegularExpression Id. */
  int CONST_VAR = 22;
  /** RegularExpression Id. */
  int TRY = 23;
  /** RegularExpression Id. */
  int CATCH = 24;
  /** RegularExpression Id. */
  int FINALLY = 25;
  /** RegularExpression Id. */
  int MODULE = 26;
  /** RegularExpression Id. */
  int EXPORT = 27;
  /** RegularExpression Id. */
  int IMPORT = 28;
  /** RegularExpression Id. */
  int FROM = 29;
  /** RegularExpression Id. */
  int AS_KW = 30;
  /** RegularExpression Id. */
  int VARIABLE = 31;
  /** RegularExpression Id. */
  int IDENT = 32;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 33;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 34;
  /** RegularExpression Id. */
  int HEX_LITERAL = 35;
  /** RegularExpression Id. */
  int STRING_LITERAL = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int MULT = 39;
  /** RegularExpression Id. */
  int DIV = 40;
  /** RegularExpression Id. */
  int MOD = 41;
  /** RegularExpression Id. */
  int ASSIGN = 42;
  /** RegularExpression Id. */
  int ADD_ASSIGN = 43;
  /** RegularExpression Id. */
  int SUB_ASSIGN = 44;
  /** RegularExpression Id. */
  int MUL_ASSIGN = 45;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 46;
  /** RegularExpression Id. */
  int MOD_ASSIGN = 47;
  /** RegularExpression Id. */
  int EQ = 48;
  /** RegularExpression Id. */
  int NEQ = 49;
  /** RegularExpression Id. */
  int LT = 50;
  /** RegularExpression Id. */
  int GT = 51;
  /** RegularExpression Id. */
  int LE = 52;
  /** RegularExpression Id. */
  int GE = 53;
  /** RegularExpression Id. */
  int AND = 54;
  /** RegularExpression Id. */
  int OR = 55;
  /** RegularExpression Id. */
  int NOT = 56;
  /** RegularExpression Id. */
  int NAMESPACE_OP = 57;
  /** RegularExpression Id. */
  int ARROW = 58;
  /** RegularExpression Id. */
  int LPAREN = 59;
  /** RegularExpression Id. */
  int RPAREN = 60;
  /** RegularExpression Id. */
  int LBRACE = 61;
  /** RegularExpression Id. */
  int RBRACE = 62;
  /** RegularExpression Id. */
  int LBRACKET = 63;
  /** RegularExpression Id. */
  int RBRACKET = 64;
  /** RegularExpression Id. */
  int SEMICOLON = 65;
  /** RegularExpression Id. */
  int COMMA = 66;
  /** RegularExpression Id. */
  int DOT = 67;
  /** RegularExpression Id. */
  int COLON = 68;
  /** RegularExpression Id. */
  int DEC = 69;
  /** RegularExpression Id. */
  int INC = 70;
  /** RegularExpression Id. */
  int ERROR = 71;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"fn\"",
    "\"return\"",
    "\"aqhe\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"break\"",
    "\"continue\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "<CONST_VAR>",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"module\"",
    "\"export\"",
    "\"import\"",
    "\"from\"",
    "\"as\"",
    "<VARIABLE>",
    "<IDENT>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<HEX_LITERAL>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"::\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"--\"",
    "\"++\"",
    "<ERROR>",
  };

}
