PARSER_BEGIN(AnalizadorLexico)

public class AnalizadorLexico {
    public static void main(String[] args) throws ParseException, java.io.FileNotFoundException {

        java.io.InputStream input;
        if (args.length > 0) {
            input = new java.io.FileInputStream(args[0]); 
        } else {
            input = System.in;
        }

        AnalizadorLexico parser = new AnalizadorLexico(input);
        
        // MOSTRAR TOKENS
        Token t;
        while ((t = parser.getNextToken()).kind != AnalizadorLexicoConstants.EOF) {
            System.out.println("TOKEN: " + tokenImage[t.kind] + " => " + t.image);
        }

        // REINICIAR PARA ANÁLISIS SINTÁCTICO
        if (args.length > 0) {
            input = new java.io.FileInputStream(args[0]);
        } else {
            input = System.in;
        }

        parser.ReInit(input);

        parser.Program();
        System.out.println("Análisis sintáctico correcto.");
    }
}

PARSER_END(AnalizadorLexico)



// ==========================================================
// Aqheran
// ==========================================================

// ==========================================================
// ESPACIOS Y COMENTARIOS
// ==========================================================
SKIP :
{
      " " | "\t" | "\r" | "\n"
}

SKIP :
{
// Comentarios de 1 y n lineas
    < "//" (~["\n", "\r"])* ("\n" | "\r" | "\r\n") >
|   < "/*" (~["*"])* ("*" (~["/"] (~["*"])* ) )* "*" "/" >
}


// ==========================================================
// PALABRAS RESERVADAS
// ==========================================================
TOKEN :
{
    < IF: "if" >
|   < ELSE: "else" >
|   < WHILE: "while" >
|   < FOR: "for" >
|   < FUNCTION: "fn" >
|   < RETURN: "return" >

// Imprimir mensajes
|   < AQHE: "aqhe" >
|   < TRUE: "true" >
|   < FALSE: "false" >
|   < NULL: "null" >
|   < BREAK: "break" >
|   < CONTINUE: "continue" >

// Uso de switch
|   < SWITCH: "switch" >
|   < CASE: "case" >
|   < DEFAULT_KW: "default" >

//Constantes
|   < CONST_VAR: "#" (["a"-"z","A"-"Z","_"]) (["a"-"z","A"-"Z","0"-"9","_"])* >
|   < TRY: "try" >
|   < CATCH: "catch" >
|   < FINALLY: "finally" >

// Tokens clave para Modularidad
|   < MODULE: "module" >
|   < EXPORT: "export" >
|   < IMPORT: "import" >
|   < FROM: "from" >
|   < AS_KW: "as" >
}


// ==========================================================
// IDENTIFICADORES Y LITERALES y VARIABLES
// ==========================================================

TOKEN :
{
    < VARIABLE: "@" (["a"-"z","A"-"Z","_"]) (["a"-"z","A"-"Z","0"-"9","_"])* >
}


TOKEN :
{
    < IDENT: (["a"-"z","A"-"Z","_"]) (["a"-"z","A"-"Z","0"-"9","_"])* >

|   < INTEGER_LITERAL: (["0"-"9"])+ >
|   < FLOAT_LITERAL: (["0"-"9"])+ "." (["0"-"9"])+ >
|   < HEX_LITERAL: "0x" (["0"-"9","a"-"f","A"-"F"])+ >

|   < STRING_LITERAL:
        ("\"" ( "\\" ["n","t","r","b","f","\\","\"","'"] | ~["\"","\\"] )* "\"" )
      | ("'" ( "\\" ["n","t","r","b","f","\\","\"","'"] | ~["'","\\"] )* "'" )
    >

}


// ==========================================================
// OPERADORES
// ==========================================================
TOKEN :
{
    < PLUS: "+" >
|   < MINUS: "-" >
|   < MULT: "*" >
|   < DIV: "/" >
|   < MOD: "%" >

|   < ASSIGN: "=" >
|   < ADD_ASSIGN: "+=" >
|   < SUB_ASSIGN: "-=" >
|   < MUL_ASSIGN: "*=" >
|   < DIV_ASSIGN: "/=" >
|   < MOD_ASSIGN: "%=" >

|   < EQ: "==" >
|   < NEQ: "!=" >
|   < LT: "<" >
|   < GT: ">" >
|   < LE: "<=" >
|   < GE: ">=" >

|   < AND: "&&" >
|   < OR: "||" >
|   < NOT: "!" >
// Operador de alcance y operador flecha
|   < NAMESPACE_OP: "::" >
|   < ARROW: "->" >
}


// ==========================================================
// SÍMBOLOS
// ==========================================================
TOKEN :
{
    < LPAREN: "(" >
|   < RPAREN: ")" >
|   < LBRACE: "{" >
|   < RBRACE: "}" >
|   < LBRACKET: "[" >
|   < RBRACKET: "]" >
|   < SEMICOLON: ";" >
|   < COMMA: "," >
|   < DOT: "." >
|   < COLON: ":" >
}


// ==========================================================
// Tokens que nos faltaron XD
// ==========================================================

TOKEN : { < DEC : "--" > }
TOKEN : { < INC : "++" > }

// ==========================================================
// ERROR TOKEN
// ==========================================================
TOKEN :
{
    < ERROR: ~[] >
}

// ==========================================================
// PARSER Aqheran
// ==========================================================

// Programa completo
void Program() :
{}
{
    ( ModuleDecl()
    | FunctionDecl()
    | Statement()
    )* <EOF>
}

// Modulos
void ModuleDecl() :
{}
{
    <MODULE> <IDENT> <LBRACE> ModuleBody() <RBRACE>
}

void ModuleBody() :
{}
{
    (ImportDecl() | ExportDecl() | FunctionDecl())*
}

void ImportDecl() :
{}
{
    <IMPORT> <IDENT> ( <AS_KW> <IDENT> )? ( <FROM> <STRING_LITERAL> )? <SEMICOLON>
}

void ExportDecl() :
{}
{
    <EXPORT> ( FunctionDecl() | <IDENT> <SEMICOLON> )
}

//funciones

void FunctionDecl() :
{}
{
    <FUNCTION> <IDENT> <LPAREN> ParamList() <RPAREN> FunctionBody()
}

void ParamList() :
{}
{
    [ <IDENT> ( <COMMA> <IDENT> )* ]
}

void FunctionBody() :
{}
{
    ( <ARROW> Expression() <SEMICOLON> )
  | ( <LBRACE> StatementList() <RBRACE> )
}

// Sentencias

void StatementList() :
{}
{
    (Statement())*
}

void PrintStatement() :
{}
{
    <AQHE> <LPAREN> [ Expression() ] <RPAREN> <SEMICOLON>
}

void Statement() :
{}
{
      IfStatement()
    | WhileStatement()
    | ForStatement()
    | ReturnStatement()
    | BreakStatement()
    | ContinueStatement()
    | SwitchStatement()
    | TryCatchStatement()
    | PrintStatement()
    | Block()
    | Expression() <SEMICOLON>
}

void Block() :
{}
{
    <LBRACE> StatementList() <RBRACE>
}

// Control de Flujo

void IfStatement() :
{}
{
    <IF> <LPAREN> Expression() <RPAREN>
    Statement()
    (
        LOOKAHEAD(<ELSE>)
        <ELSE> Statement()
    )?
}


void WhileStatement() :
{}
{
    <WHILE> <LPAREN> Expression() <RPAREN> Statement()
}

void ForStatement() :
{}
{
    <FOR> <LPAREN> [ Expression() ] <SEMICOLON> [ Expression() ] <SEMICOLON> [ Expression() ] <RPAREN> Statement()
}

void ReturnStatement() :
{}
{
    <RETURN> [ Expression() ] <SEMICOLON>
}

void BreakStatement() :
{}
{
    <BREAK> <SEMICOLON>
}

void ContinueStatement() :
{}
{
    <CONTINUE> <SEMICOLON>
}

// Switch
void SwitchStatement() :
{}
{
    <SWITCH> <LPAREN> Expression() <RPAREN> <LBRACE> (CaseBlock())* <RBRACE>
}

void CaseBlock() :
{}
{
      <CASE> Expression() <COLON> StatementList()
    | <DEFAULT_KW> <COLON> StatementList()
}

// Try y Catch

void TryCatchStatement() :
{}
{
    <TRY> Block() <CATCH> <LPAREN> <IDENT> <RPAREN> Block() [ <FINALLY> Block() ]
}

// Expresiones

void Expression() : {} { AssignmentExpression() }

void AssignmentExpression() :
{}
{
    LOOKAHEAD(2)
    (
        ( <IDENT> | <VARIABLE> )
        ( <ASSIGN> | <ADD_ASSIGN> | <SUB_ASSIGN> | <MUL_ASSIGN> | <DIV_ASSIGN> | <MOD_ASSIGN> )
        AssignmentExpression()
    )
  | OrExpression()
}



void OrExpression() :
{}
{
    AndExpression() ( <OR> AndExpression() )*
}

void AndExpression() :
{}
{
    EqualityExpression() ( <AND> EqualityExpression() )*
}

void EqualityExpression() :
{}
{
    RelationalExpression() ( ( <EQ> | <NEQ> ) RelationalExpression() )*
}

void RelationalExpression() :
{}
{
    AddExpression() ( ( <LT> | <GT> | <LE> | <GE> ) AddExpression() )*
}

void AddExpression() :
{}
{
    MultExpression() ( ( <PLUS> | <MINUS> ) MultExpression() )*
}

void MultExpression() :
{}
{
    UnaryExpression() ( ( <MULT> | <DIV> | <MOD> ) UnaryExpression() )*
}

void UnaryExpression() :
{}
{
      ( <INC> | <DEC> ) PrimaryExpression()
    | PrimaryExpression() ( <INC> | <DEC> )?
}


// Primarios

void PrimaryExpression() :
{}
{
      Literal()
    | <VARIABLE>
    | <LPAREN> Expression() <RPAREN>
    | AccessExpression()
}


void ArgList() :
{}
{
    [ Expression() ( <COMMA> Expression() )* ]
}

void AccessExpression() :
{}
{
    <IDENT>
    (
        <LPAREN> ArgList() <RPAREN>     // llamada
      | <DOT> <IDENT>                  // acceso
      | <LBRACKET> Expression() <RBRACKET>
      | <NAMESPACE_OP> <IDENT>
    )*
}

//literales
void Literal() :
{}
{
      <INTEGER_LITERAL>
    | <FLOAT_LITERAL>
    | <HEX_LITERAL>
    | <STRING_LITERAL>
    | <TRUE>
    | <FALSE>
    | <NULL>
}
